# Generated by Django 6.0.2 on 2026-02-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='encounter_class',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='start',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deathdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='race',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty',
        ),
        migrations.AddField(
            model_name='claim',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider'),
        ),
        migrations.CreateModel(
            name='ClaimTransaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PayerTransition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payer')),
            ],
        ),
    ]
