# Generated by Django 6.0.2 on 2026-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterencounter',
            name='age_at_visit',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterpatient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpatient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
