# Generated by Django 6.0.2 on 2026-04-17 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_masterencounter_age_at_visit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role_name', models.CharField(blank=True, max_length=150, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('avg_cost', 'Average Cost'), ('avg_oop', 'Average Out Of Pocket'), ('avg_coverage', 'Average Coverage'), ('visits', 'Visits'), ('patients', 'Patients'), ('hospitals', 'Hospitals')], max_length=50)),
                ('model_name', models.CharField(default='random_forest', max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('trained_from_months', models.IntegerField(default=36)),
                ('forecast_months', models.IntegerField(default=18)),
                ('source_note', models.CharField(default='master_data', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='masterpatient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterpatient',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawpatient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawpatient',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='moved_to_recycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='sleep_protection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='unsynced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterpatient',
            name='patient_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('synced', 'Synced'), ('unsynced', 'Unsynced'), ('failed', 'Failed'), ('recycle_bin', 'Recycle Bin'), ('deleted', 'Deleted')], default='uploaded', max_length=20),
        ),
        migrations.AddIndex(
            model_name='masterpatient',
            index=models.Index(fields=['patient_id', 'state', 'city'], name='core_master_patient_e55055_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpatient',
            index=models.Index(fields=['patient_id', 'state', 'city'], name='core_rawpat_patient_fbff7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterpatient',
            constraint=models.UniqueConstraint(fields=('patient_id', 'state', 'city', 'address', 'county'), name='uniq_master_patient_identity'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_developers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
