# Generated by Django 6.0.2 on 2026-04-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_developerprofile_modelartifact_masterpatient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='actual_processing_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='estimated_processing_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='total_zip_size_mb',
            field=models.FloatField(default=0),
        ),
    ]
